# Cloud Build configuration for deploying to Cloud Run
# This file deploys both frontend and backend

steps:
  # ========== BACKEND ==========
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/expenses-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/expenses-backend:latest'
      - './backend'
    id: 'build-backend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/expenses-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'expenses-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/expenses-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,GOOGLE_APPLICATION_CREDENTIALS=/secrets/bq-credentials/bq-service-account.json'
      - '--update-secrets'
      - '/secrets/bq-credentials/bq-service-account.json=bq-service-account:latest'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Get backend URL for frontend build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services describe expenses-backend --region us-central1 --format 'value(status.url)' > /workspace/backend_url.txt
        echo "Backend URL: $(cat /workspace/backend_url.txt)"
    id: 'get-backend-url'
    waitFor: ['deploy-backend']

  # ========== FRONTEND ==========
  # Build frontend Docker image with backend URL
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        docker build \
          --build-arg VITE_API_URL=$${BACKEND_URL} \
          -t gcr.io/$PROJECT_ID/expenses-frontend:$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/expenses-frontend:latest \
          .
    id: 'build-frontend'
    waitFor: ['get-backend-url']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/expenses-frontend:$COMMIT_SHA'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'expenses-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/expenses-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/expenses-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/expenses-backend:latest'
  - 'gcr.io/$PROJECT_ID/expenses-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/expenses-frontend:latest'

# Build timeout
timeout: '1800s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
